feat: added code for account trust score badges
MetaMask/permissionless-snaps-directory pull request #106
Opened 2024-02-20 17:03 UTC by satyajeetkolhapure

## Description

Updated account badges component to receive trust score from api and show corresponding badges

<img width="733" alt="image" src="https://github.com/MetaMask/permissionless-snaps-directory/assets/77279246/518e5e1e-a922-4857-b614-3f543321cf11">

### Related ticket

Fixes #9 

### Type of change

- [ ] Chore
- [ ] Bug fix
- [ ] New feature
- [ ] Documentation update

2024-02-20 18:06 UTC, alainncls approved these changes

2024-02-21 02:56 UTC, stanleyyconsensys requested changes
LGTM, some comment need to verify on your side , and i would suggest move the business logic / API call in account role tag / account info to a hook if we have time

2024-02-21 10:21 UTC, satyajeetkolhapure commented on src/features/account/components/AccountRoleTags.tsx
> +  const getRoleAttributes = (role: AccountRole) => {
I think functions are more readable, but I am fine with hashmap too

2024-02-21 10:23 UTC, satyajeetkolhapure commented on src/features/account/components/AccountRoleTags.tsx
> +        return '🧑‍💻';
Unfortunately we don't have svg for these, I got confirmation from Erik to use emoji instead. But yes svg would have been better

2024-02-21 10:23 UTC, satyajeetkolhapure commented on src/features/account/components/AccountInfo.tsx
> +      <HStack>
makes sense. I will remove it

2024-02-21 10:25 UTC, satyajeetkolhapure commented on src/features/account/components/AccountInfo.tsx
> +      </HStack>
```suggestion
```

2024-02-21 10:25 UTC, satyajeetkolhapure commented on src/features/account/components/AccountInfo.tsx
> +      <HStack>
```suggestion
```

2024-02-21 11:40 UTC, stanleyyconsensys approved these changes

2024-02-21 11:40 UTC, merged