feat: Deploy to GitHub Pages
MetaMask/permissionless-snaps-directory pull request #33
Opened 2023-12-19 16:39 UTC by alainncls

2023-12-19 23:23 UTC, Mrtenz requested changes

2023-12-19 23:23 UTC, Mrtenz commented on .github/workflows/publish-gh-pages.yml
Instead of creating a new workflow, you can just modify `publish-staging.yml` and `publish-staging-site.yml`.

2024-01-16 18:02 UTC, satyajeetkolhapure approved these changes

2024-01-18 08:48 UTC, stanleyyconsensys approved these changes
LGTM

2024-01-18 09:40 UTC, merged