feat: account profile - rating
MetaMask/permissionless-snaps-directory pull request #35
Opened 2023-12-27 09:09 UTC by stanleyyconsensys

This PR is adding a component for account profile review rating

it render star by the given parameter 'rate' and 'maxRate'

where rate is refer to the current rating star, and maxRate is refer to maximum rating, 
 
Note: Star design and colour  is not confirmed, please do not comment on the design

<img width="201" alt="image" src="https://github.com/MetaMask/permissionless-snaps-directory/assets/102275989/f56a1aef-e0af-47b6-9c67-829aff795a62">

2024-01-08 17:29 UTC, ritave approved these changes

2024-01-08 18:10 UTC, Mrtenz requested changes

2024-01-08 18:10 UTC, Mrtenz commented on src/components/Rating.tsx
> +            fill={colorMode === 'light' ? '#6A737D' : '#BBC0C5'}
Use a theme value please.

2024-01-08 18:10 UTC, Mrtenz commented on src/components/Rating.tsx
> +            fill={colorMode === 'light' ? '#BBC0C5' : '#6A737D'}
Use a theme value please.

2024-01-08 18:10 UTC, Mrtenz commented on src/components/Rating.tsx
> +    const _star: ReactElement[] = [];
```suggestion
    const stars: ReactElement[] = [];
```

2024-01-08 18:10 UTC, Mrtenz commented on src/components/icons/index.ts
> +export const StarIcon = wrapIcon(BaseStarIcon, defineMessage`MetaMask`);
These messages seem wrong.

2024-01-09 17:39 UTC, alainncls commented
Closed in favour of #41

2024-01-09 17:39 UTC, closed without merging